FROM confluentinc/cp-kafka:7.3.0

USER root
RUN mkdir /opt/prometheus && \
    chmod +rx /opt/prometheus && \
    cd /opt/prometheus && \
    wget https://raw.githubusercontent.com/confluentinc/jmx-monitoring-stacks/6.1.0-post/shared-assets/jmx-exporter/kafka_broker.yml && \
    wget https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.15.0/jmx_prometheus_javaagent-0.15.0.jar
	
USER appuser
WORKDIR /home/appuser

CMD ["/etc/confluent/docker/run"]
